$(function(){
    $(".gnb").mouseenter(function(){
        $("#header_wrap").stop().animate({"height":340});
        $(".depth2").show();
    })
    $("#header_wrap").mouseleave(function(){
        $("#header_wrap").stop().animate({"height":70});
        $(".depth2").hide();
    })
})